export * from "./Admin/Admin";
export * from "./Callback";
export * from "./Home/Home";
export * from "./Login/Login";
export * from "./NotFound/NotFound";
export * from "./profile/Profile";
export * from "./Trending/Trending";
export * from "./PagesAdmin/AdminHome";
export * from "./DetailPost/DetailPost"